In [1]:
import torch
import numpy as np

In [2]:
a = np.array([0., 1., 2., 3., 4., 5., 6.])
print(a)
print(type(a))

[0. 1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>


In [3]:
print("Shape:", a.shape)
print("Rank: ", a.ndim)

Shape: (7,)
Rank:  1


In [8]:
t = torch.FloatTensor([i for i in range(7)])
print(t)
print(type(t))

tensor([0., 1., 2., 3., 4., 5., 6.])
<class 'torch.Tensor'>


In [14]:
print(t.ndim)
print(t.shape)
print("Shape:", t.size())
print(t[0], t[1], t[-1])
print((t[2:5]), t[4:-1])
print(t[:3], t[1:])

1
torch.Size([7])
Shape: torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1., 2.]) tensor([1., 2., 3., 4., 5., 6.])


In [15]:
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [17]:
print("Rank:", t.ndim, t.dim())
print("Shape:", t.shape, t.size())


Rank: 2 2
Shape: torch.Size([4, 3]) torch.Size([4, 3])


In [20]:
print(t[:, 1]) #행 전체다, 1열
print(t[1, :2])

tensor([ 2.,  5.,  8., 11.])
tensor([4., 5.])


In [21]:
t = torch.FloatTensor([
                    [
                        [[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                        
                        [[13, 14, 15, 16],
                         [17, 18, 19, 20],
                         [21, 22, 23, 24]]
                        
                        ]
                    ])

In [23]:
print(t.shape)
print(t.ndim)

torch.Size([1, 2, 3, 4])
4


In [24]:
#Matrix Multiplication, Element Multiplication
t1 = torch.FloatTensor([[1, 2],
                        [3, 4]]) #2, 2
t2 = torch.FloatTensor([[1], 
                        [2]]) #2, 1
print("Shape is :", t1.shape, t2.shape)

Shape is : torch.Size([2, 2]) torch.Size([2, 1])


In [30]:
print(t1.matmul(t2)) #(2, 2) x (2, 1) = (2, 1)
print(t1@t2)

tensor([[ 5.],
        [11.]])
tensor([[ 5.],
        [11.]])


In [28]:
print(t1.mul(t2))
print(t1*t2)

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [31]:
t1 = torch.FloatTensor([[1, 2]])
t2 = torch.FloatTensor([[2, 2]])
print(t1+t2)

tensor([[3., 4.]])


In [32]:
t3 = torch.FloatTensor([3])
print(t1+t3) #Broad Casting

tensor([[4., 5.]])


In [36]:
t1 = torch.FloatTensor([[1, 2]])
print(t1.shape)
t3 = torch.FloatTensor([[3], [4]])
print(t3.shape)
print(t1+t3)

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


In [43]:
t = torch.FloatTensor([[1, 2], 
                        [3, 4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))
print(t.mean(axis=0))


tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])
tensor([2., 3.])


In [46]:
print(t.sum())
print(t.sum(axis=0))
print(t.sum(axis=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [56]:
#argmax
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(t.max())
#print(t.max(dim=0)) #value, index
print(t.max(dim=0)[1])
torch.argmax(t)#단일차원일때 argmax
torch.argmax(torch.FloatTensor([0, 7, 2, 3, 4, 5, 6]))

tensor(4.)
tensor([1, 1])


tensor(1)

In [59]:

t = np.array([
                [
                    [[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]],
                    
                    [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                    
                    ]
                ])
ft = torch.FloatTensor(t)
print(type(ft))
print(type(t))
print(t.shape)
print(ft.shape)

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
(1, 2, 3, 4)
torch.Size([1, 2, 3, 4])


In [62]:
#(1, 2, 3, 4) x (3, 5)
#-> (xxxx, 3) x (3, 5)
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)
print(ft.reshape(-1, 3))

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]])
torch.Size([8, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]])


In [68]:
#Squeeze, unsqueeze로 텐서의 차원을 늘리거나 줄여줄 수 있습니다.
ft.shape
print(ft)
print(ft.squeeze())
sft = ft.squeeze()
print(ft.squeeze().shape)

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])
tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
torch.Size([2, 3, 4])


In [69]:
print(sft.unsqueeze(0))
print(sft.unsqueeze(0).shape)

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])
torch.Size([1, 2, 3, 4])


In [71]:
lt = torch.LongTensor([1, 2, 3, 4])
lt.float()

tensor([1., 2., 3., 4.])

In [75]:
sft.long()
#tensor -> numpy
print(sft.numpy())
n = sft.numpy()
#numpy -> tensor
print(torch.Tensor(n))

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]
tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


In [76]:
#Concatenation
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = torch.FloatTensor([[5, 6],
                       [7, 8]])
#Vertical Stack
[[1, 2],
 [3, 4],
 [5 ,6],
 [7, 8]]
#Horizontal Stack
[[1, 2, 5 ,6],
 [3, 4, 7, 8]]
v = torch.cat([x, y], dim=0) #Vertical
h = torch.cat([x, y], dim=1) #Horizontal 

In [78]:
torch.vstack([x, y])
torch.hstack([x, y])
torch.stack([x, y], dim=0)
torch.stack([x, y], dim=1)
print(v)
print(h)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [79]:
t = torch.FloatTensor([[0, 1, 2],
                       [2, 1, 0]])
print(t)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [80]:
print(torch.zeros_like(t))
print(torch.ones_like(t))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
